### ISSUE TITLE
No module named 'main.utils.libkdtree.pykdtree.kdtree'

### ISSUE THREAD

**Issue by howardgriffin** [Kulbear/object-wakeup#1]
Nice work! 
But I have encountered the problem, how can I fix this?

**Comment by howardgriffin** [comment]
I noticed  here https://github.com/Kulbear/object-wakeup/blob/62cfb70aa6369aadbca24fd1d51241f2db86e494/setup.py#L78 
 Howevery   there seems no 'main/dmc/' in the code.

**Comment by Kulbear** [comment]
Hi @howardgriffin ,
Thanks for reaching out, I will check tomorrow and let you know about it.
In the meantime, can you try to copy the `dmc` directory from [this repo](https://github.com/autonomousvision/occupancy_networks/tree/master/im2mesh/dmc)?

**Comment by howardgriffin** [comment]
Thank you for you reply! That works！

> 你好@howardgriffin, 感谢您与我们联系，我明天会检查并让您知道。 同时，您可以尝试从[这个 repo](https://github.com/autonomousvision/occupancy_networks/tree/master/im2mesh/dmc)`dmc`复制目录吗？[](https://github.com/autonomousvision/occupancy_networks/tree/master/im2mesh/dmc)
